name: CI/CD Pipeline

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      pages: write
      id-token: write

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@latest
      
    - name: Configure Maven Settings
      run: |
        mkdir -p ~/.m2
        echo "<settings><mirrors><mirror><id>central</id><url>https://repo1.maven.org/maven2</url><mirrorOf>*</mirrorOf></mirror></mirrors></settings>" > ~/.m2/settings.xml

    - name: Run Tests and Generate Reports
      run: |
        # Executar os testes e gerar relatórios
        mvn clean test
        
        # Criar diretório para artefatos
        mkdir -p artifacts
        
        # Copiar evidências e relatórios
        if [ -d "target/evidencias" ]; then
          cp -r target/evidencias artifacts/
        fi
        if [ -d "target/surefire-reports" ]; then
          cp -r target/surefire-reports artifacts/
        fi
        if [ -d "target/allure-results" ]; then
          cp -r target/allure-results artifacts/
        fi
        
        # Gerar relatório Allure
        mvn allure:report
        
        # Copiar relatório Allure
        if [ -d "target/site/allure-maven-plugin" ]; then
          cp -r target/site/allure-maven-plugin artifacts/allure-report
        fi
        
        # Criar arquivo de log
        echo "Test execution completed at $(date)" > artifacts/execution.log
        
        # Zipar artefatos
        cd artifacts
        zip -r ../test-artifacts.zip ./*
        cd ..

    - name: Upload Test Results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: test-artifacts.zip
        
    - name: Deploy Allure Report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./artifacts/allure-report 