name: CI/CD Pipeline

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@latest
    
    - name: Build and Test
      run: |
        mvn clean install -DskipTests
        mvn test
      continue-on-error: true
    
    - name: Check directories
      if: always()
      run: |
        echo "Listing target directory:"
        ls -la target/ || true
        echo "Creating directories if they don't exist:"
        mkdir -p target/evidencias
        mkdir -p target/surefire-reports
        echo "Directory contents after creation:"
        ls -la target/
        
    - name: Upload Test Evidence
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-evidence
        path: |
          target/evidencias/**
          target/surefire-reports/**
        if-no-files-found: warn 