name: CI/CD Pipeline

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@latest
      
    - name: Run Tests
      run: |
        mvn clean test
        mkdir -p target/artifacts
        cp -r target/evidencias target/artifacts/ || true
        cp -r target/surefire-reports target/artifacts/ || true
    
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: target/artifacts/
        retention-days: 30 