name: CI/CD Pipeline

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

permissions:
  contents: read
  actions: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Create test file
      run: |
        mkdir -p test-output
        echo "Test content" > test-output/test.txt
        ls -la test-output/
    
    - name: Upload test file
      uses: actions/upload-artifact@v2
      with:
        name: test-files
        path: test-output/ 