name: CI/CD Pipeline

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@latest
    
    - name: Create directories for artifacts
      run: |
        mkdir -p target/evidencias
        mkdir -p target/surefire-reports
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    - name: Run Tests
      run: mvn test
      continue-on-error: true  # Permite continuar mesmo se os testes falharem
    
    - name: Archive test results
      if: always()  # Executa mesmo se os passos anteriores falharem
      uses: actions/upload-artifact@v3
      with:
        name: test-evidence
        path: target/evidencias/
        if-no-files-found: warn  # Apenas avisa se não encontrar arquivos, sem falhar
    
    - name: Archive test reports
      if: always()  # Executa mesmo se os passos anteriores falharem
      uses: actions/upload-artifact@v3
      with:
        name: test-reports
        path: target/surefire-reports/
        if-no-files-found: warn  # Apenas avisa se não encontrar arquivos, sem falhar 