name: CI/CD Pipeline

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2

    - name: Create and Upload Artifact
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Create test output
        mkdir -p artifact
        echo "Test content" > artifact/test.txt
        echo "Created file:"
        cat artifact/test.txt
        
        # Create artifact using REST API
        cd artifact
        zip -r ../artifact.zip ./*
        cd ..
        
        echo "Uploading artifact..."
        curl -X POST \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          -F "workflow_run=${{ github.run_id }}" \
          -F "name=test-artifact" \
          -F "file=@artifact.zip" \
          "https://api.github.com/repos/${{ github.repository }}/actions/artifacts" 